module(load="omhttp")

template(name="MyJSONTemplate" type="string" string="{\"message\":\"%msg%\",\"host\":\"%hostname%\",\"severity\":\"%syslogseverity-text%\"}")

action(
    type="omhttp"
    server="scleravdmsnetworkgateway"
    serverport="8888"
    usehttps="off"
    restpath="syslogs"
    template="MyJSONTemplate"
    retry="on"
    batch="off"
)
