module(load="omfwd")

template(name="MyJSONTemplate" type="string" string="{\"message\":\"%msg%\",\"host\":\"%hostname%\",\"severity\":\"%syslogseverity-text%\"}")

action(
    type="omfwd"
    target="scleravdmsnetworkgateway"
    port="7777"
    protocol="udp"
    template="MyJSONTemplate"
)
