module(load="omhttp")  # For sending to your Spring Boot application
module(load="omfwd")   # For forwarding raw syslog messages to other servers

template(name="MyJSONTemplate" type="string" string="{\"message\":\"%msg%\",\"host\":\"%hostname%\",\"severity\":\"%syslogseverity-text%\"}")

# 1. Action to send logs Spring Boot application (HTTP POST)
# uses the specific JSON template defined.
action(
    type="omhttp"
    server="scleravdmsnetworkgateway"  # Hostname/IP of Spring Boot server
    serverport="8888"       # Spring Boot server's port
    usehttps="off"
    restpath="syslogs"
    template="MyJSONTemplate"
    retry="on"
    batch="off"
)