#!/bin/bash

# generate_rsyslog_forwarding_conf.sh

# Define the path where the final rsyslog config will be written
CONFIG_FILE="/etc/rsyslog.d/forwarding.conf"

# The placeholder for the forwarding IP
# This script expects the FORWARDING_IP environment variable to be set.
# If not set, it will output a warning and proceed without forwarding or exit,
# depending on how critical this is. For now, we'll make it generate nothing if not set.

# Start with a clean file
> "$CONFIG_FILE" # This truncates the file, effectively clearing it

# Add comments
echo "# Generated by generate_rsyslog_forwarding_conf.sh (dynamic IP)" >> "$CONFIG_FILE"
echo "# This file forwards syslogs based on the FORWARDING_IP environment variable." >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

if [ -z "$FORWARDING_IP" ]; then
  echo "Warning: FORWARDING_IP environment variable is not set." >> "$CONFIG_FILE"
  echo "         Rsyslog forwarding will NOT be configured." >> "$CONFIG_FILE"
  echo "# No forwarding configured due to missing FORWARDING_IP" >> "$CONFIG_FILE"
  echo "Generated empty forwarding configuration (no IP set) at $CONFIG_FILE"
else
  echo "Dynamically setting rsyslog forwarding IP to: $FORWARDING_IP" >> "$CONFIG_FILE"
  echo "" >> "$CONFIG_FILE"
  echo "# Forward logs to $FORWARDING_IP" >> "$CONFIG_FILE"
  echo "*.* action(type=\"omfwd\" target=\"$FORWARDING_IP\" port=\"514\" protocol=\"udp\")" >> "$CONFIG_FILE"
  echo "" >> "$CONFIG_FILE"
  echo "Generated rsyslog forwarding configuration at $CONFIG_FILE with IP: $FORWARDING_IP"
fi

#docker run -d \
 #  --name my-sclera-instance \
 #  -e FORWARDING_IP="10.2.32.30" \
 #  -e NETWORK_ADDRESS="10.2.32.99" \
 #  -e AGENT_ID="VDMS385" \
 #  -e DOCKER_ID="your_specific_docker_instance_id_here" \
 #  sclera_image