#!/bin/bash

# This script generates the rsyslog forwarding configuration file.
# It reads IP addresses from multiple environment variables:
# SYSLOG_TARGET_IP_1, SYSLOG_TARGET_IP_2, SYSLOG_TARGET_IP_3, SYSLOG_TARGET_IP_4, SYSLOG_TARGET_IP_5
# If an environment variable is not set or is empty, that target is skipped.

CONFIG_FILE="/etc/rsyslog.d/forwarding.conf"

# Define an array of environment variable names to check
FORWARD_IP_ENV_VARS=(
    "SYSLOG_TARGET_IP_1"
    "SYSLOG_TARGET_IP_2"
    "SYSLOG_TARGET_IP_3"
    "SYSLOG_TARGET_IP_4"
    "SYSLOG_TARGET_IP_5"
)

# Start with a clean file and add comments
echo "# Generated by generate_rsyslog_forwarding_conf.sh" > "$CONFIG_FILE"
echo "# This file forwards syslogs to target servers specified via environment variables." >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

# Flag to check if any forwarding rules were added
ANY_FORWARDING_ADDED=0

# Loop through each environment variable name
for env_var_name in "${FORWARD_IP_ENV_VARS[@]}"; do
    # Get the value of the environment variable indirectly
    target_ip=$(eval echo "\$$env_var_name")

    # Check if the environment variable is set and not empty
    if [ -n "$target_ip" ]; then
        # Remove any leading/trailing whitespace from the IP address
        trimmed_ip=$(echo "$target_ip" | xargs)

        # Skip if the IP is empty after trimming
        if [ -z "$trimmed_ip" ]; then
            continue
        fi

        echo "Found environment variable $env_var_name with IP: $trimmed_ip"
        # Add a comment for the specific forwarding rule
        echo "# Forward logs to $trimmed_ip (from $env_var_name)" >> "$CONFIG_FILE"
        # Add the rsyslog action.
        # *.* means all facilities and all priorities (all logs).
        # type="omfwd" is the output module for forwarding.
        # target specifies the destination IP.
        # port specifies the destination port (514 as requested).
        # protocol="udp" specifies the UDP protocol.
        echo "*.* action(type=\"omfwd\" target=\"$trimmed_ip\" port=\"514\" protocol=\"udp\")" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
        ANY_FORWARDING_ADDED=1
    fi
done

# If no forwarding rules were added, add a comment to the config file
if [ "$ANY_FORWARDING_ADDED" -eq 0 ]; then
    echo "# No SYSLOG_TARGET_IP_X environment variables found or they were empty. No forwarding rules added." >> "$CONFIG_FILE"
fi

echo "Generated rsyslog forwarding configuration at $CONFIG_FILE."
# Display the generated content for verification (optional, for debugging)
# cat "$CONFIG_FILE"
