#!/bin/bash

# This script generates the rsyslog forwarding configuration file with a hardcoded IP address.

CONFIG_FILE="/etc/rsyslog.d/forwarding.conf"
HARDCODED_IP="10.2.31.30" # The IP address you want to hardcode for forwarding

# Start with a clean file and add comments
echo "# Generated by generate_rsyslog_forwarding_conf.sh" > "$CONFIG_FILE"
echo "# This file forwards syslogs to a hardcoded target server." >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

# Add a comment for the specific forwarding rule
echo "# Forward logs to $HARDCODED_IP" >> "$CONFIG_FILE"
# Add the rsyslog action.
# *.* means all facilities and all priorities (all logs).
# type="omfwd" is the output module for forwarding.
# target specifies the destination IP.
# port specifies the destination port (514 as requested).
# protocol="udp" specifies the UDP protocol.
echo "*.* action(type=\"omfwd\" target=\"$HARDCODED_IP\" port=\"514\" protocol=\"udp\")" >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

echo "Generated rsyslog forwarding configuration at $CONFIG_FILE with hardcoded IP: $HARDCODED_IP"
# Display the generated content for verification (optional, for debugging)
# cat "$CONFIG_FILE"
