# /etc/rsyslog.conf

# Load modules
module(load="imuxsock")  # For local syslog
module(load="imudp")     # For receiving syslog over UDP
module(load="imtcp")     # For receiving syslog over TCP

# Inputs
input(type="imudp" port="514")
input(type="imtcp" port="514")

# Include configs from rsyslog.d
include(file="/etc/rsyslog.d/*.conf")
