# Load modules
module(load="imuxsock")
module(load="imudp")
module(load="imtcp")
module(load="omfwd")

# TCP and UDP inputs
input(type="imudp" port="514")
input(type="imtcp" port="514")

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf")
