# Set root category priority to INFO and its only appender to DailyRollingFileAppender.
log4j.rootCategory=INFO, LOGFILE

# Set the enterprise logger category to FATAL and its only appender to DailyRollingFileAppender.
log4j.logger.org.apache.axis.enterprise=FATAL, LOGFILE

# LOGFILE is set to be a DailyRollingFileAppender appender using a PatternLayout.
log4j.appender.LOGFILE = org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOGFILE.File=./logs/app_log.log
log4j.appender.LOGFILE.Append = true
log4j.appender.LOGFILE.Threshold=ALL
log4j.appender.LOGFILE.DatePattern ='.'yyyy-MM-dd
log4j.appender.LOGFILE.layout = org.apache.log4j.PatternLayout
log4j.appender.LOGFILE.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %c{1} [%p] %m%n

